name: itemis
description: A solution to coding puzzles by itemis.
version: 1.0.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  equatable: ^2.0.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  test_cov_console: ^0.2.2
